version: '3'

env:
  CONFIG_PATH: '{{.PWD}}/config'
  BREWFILE_PATH: '{{.CONFIG_PATH}}/brew/Brewfile'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    desc: List tasks (default)
    cmds:
      - cmd: task -l
        silent: true

  brew:install:
    desc: Installs brew (https://brew.sh/)
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  brew:freeze:
    desc: Creates/overwrites a brewfile based on current brew config (like pip freeze)
    cmds:
      - brew bundle dump --force --file='{{.BREWFILE_PATH}}'

  brew:bundle:check:
    desc: Installs everything specified in a Brewfile and uninstall what's installed but not listed in the file
    cmds:
      - brew bundle check --file='{{.BREWFILE_PATH}}'

  brew:bundle:install:
    desc: Installs everything specified in a Brewfile
    cmds:
      - brew bundle install --file='{{.BREWFILE_PATH}}'

  brew:bundle:cleanup:
    desc: Uninstall all dependencies not listed from the Brewfile.
    cmds:
      - brew bundle cleanup --force --file='{{.BREWFILE_PATH}}'

  zsh:create-powerlevel10k-symlink:
    desc: Creates a symlink for powerlevel10k in the zsh directory.
    cmds:
      - mkdir -p config/zsh/.oh-my-zsh/custom/themes || true
      - ln -sf ../../../../powerlevel10k config/zsh/.oh-my-zsh/custom/themes/powerlevel10k

  ollama:load-models:
    desc: Loads all Ollama Modelfiles
    cmds:
      - |
        for f in ~/.ollama/models/*.Modelfile; do
          name=$(basename "$f" .Modelfile)
          echo $name
          ollama create "$name" -f "$f"
        done

  stow:stow:
    desc: Stows the dotfiles in the local home dir
    cmds:
      - task: git:submodules:update
      - for:
          - aichat
          - alacritty
          - borders
          - code
          - continue
          - crush
          - direnv
          - ghostty
          - git
          - kitty
          - lsd
          - nano
          - nvim
          - ollama
          - skhd
          - ssh
          - task
          - tmux
          - yabai
          - yazi
          - zsh
        cmd: stow {{.CLI_ARGS}} --dir={{.CONFIG_PATH}} --target=$HOME {{ .ITEM }}

  stow:simulate:
    desc: Simulates the stowing of dotfiles in the local home dir (no harm done)
    cmds:
      - task: stow:stow
        vars: { CLI_ARGS: '-nSv' }

  stow:unstow:
    desc: Unstows the dotfiles in the local home dir
    cmds:
      - task: stow:stow
        vars: { CLI_ARGS: '-D' }

  git:submodules:update:
    desc: Initialize submodules
    cmds:
      - git submodule update --init --recursive
      - task: zsh:create-powerlevel10k-symlink

  menu:
    desc: "Interactive task picker"
    cmds:
      - cmd: |
              # Get list of available tasks (skip the first "task: Available tasks..." line)
              TASKS=$(task --list | tail -n +2 | sed 's/^[[:space:]]*//')

              # Use gum to choose a task
              SELECTED_TASK=$(echo "$TASKS" | gum choose)

              # If user selected a task, run it
              if [[ -n "$SELECTED_TASK" ]]; then
                task "$SELECTED_TASK"
              fi
        silent: true
