version: '3'

tasks:

  default:
    desc: List tasks (default)
    cmds:
      - cmd: task -l
        silent: true

  apps:chrome:new-window:
    desc: Creates a new Chrome window
    cmds:
      - open -na "Google Chrome"

  macos:space:create:
    desc: Creates a new macOS space
    cmds:
      - yabai -m space --create

  borders:start:
    desc:
    cmds:
      - ~/.config/borders/bordersrc

  yabai:install:
    desc: Installs yabai
    cmds:
      - brew install koekeishiya/formulae/yabai

  yabai:upgrade:
    desc: Upgrades yabai
    cmds:
      - brew upgrade yabai

  yabai:start:
    desc: Starts the yabai service
    cmds:
      - yabai --start-service
      - task: borders:start

  yabai:stop:
    desc: Stops the yabai service
    cmds:
      - yabai --stop-service

  yabai:restart:
    desc: Restarts the yabai service
    cmds:
      - yabai --restart-service
      - task: borders:start

  yabai:configure-scripting-addition:
    desc: |
      Configure scripting addition, as per https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

      This is only required for some features to work.
      We don't use them, or this.
    cmds:
      - echo {{.USER}} {{.HASH}} {{.YABAI}}
      - sudo touch {{.TARGET_FILE}}
      - echo "{{.CONTENT_LINE}}"
      # If this doesn't work, edit file manually e.g. sudo micro /private/etc/sudoers.d/yabai
      - sudo echo "{{.CONTENT_LINE}}" > {{.TARGET_FILE}}
      - |
        yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
      - sudo yabai --load-sa
    vars:
      TARGET_FILE: /private/etc/sudoers.d/yabai
      USER:
        sh: whoami
      YABAI:
        sh: which yabai
      HASH:
        sh: shasum -a 256 {{.YABAI}}
      CONTENT_LINE: "{{.USER}} ALL=(root) NOPASSWD: sha256:{{.HASH}} {{.YABAI}} --load-sa"

  skhd:start:
    desc: Starts the skhd service
    cmds:
      - skhd --start-service

  skhd:stop:
    desc: Stops the skhd service
    cmds:
      - skhd --stop-service

  skhd:restart:
    desc: Restarts the skhd service
    cmds:
      - task: skhd:stop
      - task: skhd:start

  caffeinate:caffeinate:
    desc: Keeps the mac and its screen on, even when closed.
    cmds:
      - caffeinate -d

  caffeinate:manual:
    desc: Displays caffeinate manual
    cmds:
      - man caffeinate

  template:use:python:
    desc: Creates a new python project based on our cookiecutter template
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cookiecutter gh:legomb/cookiecutter-template-python
